create schema IF NOT EXISTS DIMAS_SIS;

USE DIMAS_SIS;

SHOW databases;

CREATE TABLE IF NOT EXISTS USUARIOS(
ID_USUARIO INT NOT NULL auto_increment,
NOME varchar(100) NOT NULL,
USUARIO varchar(100) NOT NULL UNIQUE,
SENHA varchar(100) NOT NULL,
ID_PERFIL INT NOT NULL,
EMAIL VARCHAR(100) NOT NULL,

primary key (ID_USUARIO)
);

CREATE TABLE IF NOT EXISTS PERFIL(
ID_PERFIL INT NOT NULL AUTO_INCREMENT,
PERFIL VARCHAR(30),

PRIMARY KEY (ID_PERFIL)
);

CREATE TABLE IF NOT EXISTS PERFIS(
ID_PERFIL INT NOT NULL auto_increment,
CADASTRO_DE_CLIENTES BOOL NOT NULL,
CADASTRO_DE_PRODUTOS BOOL NOT NULL,
CADASTRO_DE_SERVICOS BOOL NOT NULL,
CADASTRO_DE_USUARIOS BOOL NOT NULL,
CADASTRO_DE_ESTOQUE BOOL NOT NULL,
VENDAS BOOL NOT NULL,
CLIENTES_POR_REGIAO BOOL NOT NULL,
COMPRAS_POR_PERIODO BOOL NOT NULL,
RANKING_DE_CLIENTES BOOL NOT NULL,
PARETTO BOOL NOT NULL,

PRIMARY KEY (ID_PERFIL)
);

SHOW TABLES;